# FRED Series IDs for critical indicators
fred_series_ids = {
    "Real GDP": "GDPC1",                     # Real Gross Domestic Product (Quarterly, SA)
    "Nominal GDP": "GDP",                    # Nominal Gross Domestic Product (Quarterly, SA)
    "GDP Deflator": "GDPDEF",                # GDP Price Deflator (Quarterly, SA)
    "CPI Inflation": "CPIAUCSL",             # Consumer Price Index for All Urban Consumers (Monthly, SA)
    "Core CPI": "CPILFESL",                 # Core CPI (excl. Food and Energy, Monthly, SA)
    "PCE Inflation": "PCEPI",                # Personal Consumption Expenditures Price Index (Monthly, SA)
    "Core PCE": "PCEPILFE",                 # Core PCE Price Index (excl. Food and Energy, Monthly, SA)
    "Producer Price Index": "PPIACO",        # PPI for All Commodities (Monthly, NSA)
    "Core PPI": "PPIFGS",                   # PPI for Final Goods (Monthly, SA)
    "Unemployment Rate": "UNRATE",           # Civilian Unemployment Rate (Monthly, SA)
    "Nonfarm Payrolls": "PAYEMS",            # Total Nonfarm Payroll Employment (Monthly, SA)
    "Labor Force Participation": "CIVPART",  # Civilian Labor Force Participation Rate (Monthly, SA)
    "U-6 Unemployment": "U6RATE",            # Broader Unemployment Rate (Monthly, SA)
    "Average Hourly Earnings": "CES0500000003", # Avg Hourly Earnings of Production Employees (Monthly, SA)
    "Fed Funds Rate": "FEDFUNDS",            # Effective Federal Funds Rate (Monthly)
    "2-Year Treasury Yield": "DGS2",         # 2-Year Treasury Note Yield (Daily)
    "10-Year Treasury Yield": "DGS10",       # 10-Year Treasury Note Yield (Daily)
    "30-Year Treasury Yield": "DGS30",       # 30-Year Treasury Bond Yield (Daily)
    "3-Month Treasury Bill": "TB3MS",        # 3-Month Treasury Bill Secondary Market Rate (Monthly)
    "10-Year TIPS Spread": "T10YIE",        # 10-Year Breakeven Inflation Rate (Daily)
    "S&P 500 Index": "SP500",               # S&P 500 Index (Daily)
    "VIX Volatility Index": "VIXCLS",       # CBOE Volatility Index (Daily)
    "Consumer Confidence": "UMCSENT",       # University of Michigan Consumer Sentiment (Monthly)
    "Retail Sales": "RSXFS",                # Advance Retail Sales (Monthly, SA)
    "Industrial Production": "INDPRO",       # Industrial Production Index (Monthly, SA)
    "Capacity Utilization": "TCU",           # Total Capacity Utilization (Monthly, SA)
    "Manufacturing PMI": "NAPMPMI",         # ISM Manufacturing PMI (Monthly)
    "Non-Manufacturing PMI": "NAPMNMI",     # ISM Non-Manufacturing PMI (Monthly)
    "Housing Starts": "HOUST",              # Housing Starts (Monthly, SA)
    "Building Permits": "PERMIT",            # Building Permits (Monthly, SA)
    "Existing Home Sales": "EXHOSLUS",      # Existing Home Sales (Monthly, SA)
    "New Home Sales": "HSN1F",              # New Single-Family Home Sales (Monthly, SA)
    "Case-Shiller Home Price": "CSUSHPINSA", # S&P/Case-Shiller U.S. National Home Price Index (Monthly, SA)
    "Mortgage Rates 30-Year": "MORTGAGE30US", # 30-Year Fixed Mortgage Rate (Weekly)
    "Personal Income": "PI",                 # Personal Income (Monthly, SA)
    "Personal Consumption": "PCEC",          # Personal Consumption Expenditures (Monthly, SA)
    "Personal Savings Rate": "PSAVERT",      # Personal Saving Rate (Monthly, SA)
    "Disposable Income": "DSPIC96",         # Real Disposable Personal Income (Monthly, SA)
    "Consumer Credit": "TOTALSL",           # Total Consumer Credit Outstanding (Monthly, SA)
    "Trade Balance": "BOPGSTB",             # Goods and Services Trade Balance (Monthly, SA)
    "Exports": "EXPGS",                     # U.S. Exports of Goods and Services (Monthly, SA)
    "Imports": "IMPGS",                     # U.S. Imports of Goods and Services (Monthly, SA)
    "Current Account Balance": "NETFI",      # Net International Investment Position (Quarterly)
    "M2 Money Supply": "M2SL",              # M2 Money Stock (Monthly, SA)
    "M1 Money Supply": "M1SL",              # M1 Money Stock (Monthly, SA)
    "Velocity of M2": "M2V",                # Velocity of M2 Money Stock (Quarterly)
    "Bank Reserves": "TOTRESNS",            # Total Reserves of Depository Institutions (Monthly, NSA)
    "Commercial Bank Loans": "TOTLL",       # Total Loans and Leases at Commercial Banks (Monthly, SA)
    "Corporate Bond Yield AAA": "AAA",      # Moody’s Seasoned Aaa Corporate Bond Yield (Monthly)
    "Corporate Bond Yield BAA": "BAA",      # Moody’s Seasoned Baa Corporate Bond Yield (Monthly)
    "High Yield Spread": "BAMLH0A0HYM2",    # ICE BofA US High Yield Index Option-Adjusted Spread (Daily)
    "TED Spread": "TEDRATE",                # TED Spread (Daily)
    "Yield Curve 10Y-2Y": "T10Y2Y",         # 10-Year minus 2-Year Treasury Yield Spread (Daily)
    "Yield Curve 10Y-3M": "T10Y3M",         # 10-Year minus 3-Month Treasury Yield Spread (Daily)
    "Real Retail Sales": "RRSFS",           # Real Retail and Food Services Sales (Monthly, SA)
    "Durable Goods Orders": "DGORDER",      # Manufacturers’ New Orders: Durable Goods (Monthly, SA)
    "Nondurable Goods Orders": "NDGORDER",  # Manufacturers’ New Orders: Nondurable Goods (Monthly, SA)
    "Business Inventories": "BUSINV",       # Total Business Inventories (Monthly, SA)
    "Inventory to Sales Ratio": "ISRATIO",  # Total Business Inventories to Sales Ratio (Monthly, SA)
    "Leading Economic Index": "USSLIND",    # Conference Board Leading Economic Index (Monthly)
    "Coincident Economic Index": "USSLCOI", # Conference Board Coincident Economic Index (Monthly)
    "Lagging Economic Index": "USSLAGI",    # Conference Board Lagging Economic Index (Monthly)
    "Initial Jobless Claims": "ICSA",       # Initial Jobless Claims (Weekly, SA)
    "Continuing Claims": "CCSA",            # Continuing Jobless Claims (Weekly, SA)
    "Productivity": "OPHNFB",               # Nonfarm Business Sector Productivity (Quarterly, SA)
    "Unit Labor Costs": "ULCNFB",           # Nonfarm Business Sector Unit Labor Costs (Quarterly, SA)
    "Employment Cost Index": "ECI",         # Employment Cost Index (Quarterly, SA)
    "Consumer Debt Service Ratio": "TDSP",  # Household Debt Service Payments as % of Disposable Income (Quarterly)
    "Household Debt to GDP": "HDTGPD",      # Household Debt to GDP Ratio (Quarterly)
    "Commercial Real Estate Prices": "CRE", # Commercial Real Estate Price Index (Quarterly)
    "Construction Spending": "TTLCONS",     # Total Construction Spending (Monthly, SA)
    "Vehicle Sales": "TOTALSA",             # Total Vehicle Sales (Monthly, SA)
    "Oil Prices WTI": "DCOILWTICO",        # Crude Oil Prices: West Texas Intermediate (Daily)
    "Gold Ore PPI": "WPU10210501",          # Producer Price Index for Gold Ores (Monthly, NSA)
    "Commodity Price Index": "PALLFNFINDEXQ", # Global Price Index of All Commodities (Quarterly)
    "Baltic Dry Index": "BALTIC",           # Baltic Dry Index (Daily)
    "Corporate Profits": "CP",              # Corporate Profits After Tax (Quarterly, SA)
    "Federal Debt to GDP": "GFDEGDQ188S",  # Federal Debt as % of GDP (Quarterly)
    "Budget Deficit": "MTSR133FMS",        # Federal Surplus or Deficit (Monthly)
    "Consumer Price Index Shelter": "CUSR0000SAH1", # CPI: Shelter (Monthly, SA)
    "Real Personal Consumption": "PCE96",   # Real Personal Consumption Expenditures (Monthly, SA)
    "Export Price Index": "IQ",             # Export Price Index (Monthly, SA)
    "Import Price Index": "IQIM",           # Import Price Index (Monthly, SA)
    "Small Business Optimism": "SBOPTIM",   # NFIB Small Business Optimism Index (Monthly)
    "Consumer Loans": "CONSUMER",           # Consumer Loans at All Commercial Banks (Monthly, SA)
    "Bank Prime Rate": "MPRIME",            # Bank Prime Loan Rate (Monthly)
    "Delinquency Rate Mortgages": "DRSFRMACBS", # Delinquency Rate on Single-Family Mortgages (Quarterly)
    "Delinquency Rate Consumer Loans": "DRCLACBS", # Delinquency Rate on Consumer Loans (Quarterly)
    "Net Interest Margin": "USNIM",         # Net Interest Margin for U.S. Banks (Quarterly)
    "Bank Credit": "TOTBKCR",               # All Commercial Banks Credit (Monthly, SA)
    "Money Market Funds": "MMMFFAQ",        # Money Market Funds Assets (Quarterly)
    "Housing Affordability": "FIXHAI",      # Housing Affordability Index (Monthly)
    "Retail Inventories": "RETAILIRSA",     # Retail Inventories (Monthly, SA)
    "Chicago Fed National Activity": "CFNAI", # Chicago Fed National Activity Index (Monthly)
    "Philly Fed Manufacturing": "MPHIL",    # Philadelphia Fed Manufacturing Index (Monthly)
    "Empire State Manufacturing": "GACMAN", # Empire State Manufacturing Survey (Monthly)
    "Pending Home Sales": "PHSI",           # Pending Home Sales Index (Monthly, SA)
    "Credit Card Debt": "CCBCRV",           # Revolving Consumer Credit Owned by Commercial Banks (Monthly, SA)
}